//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA44TEAM08b_SFBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EmployeeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<double> Salary { get; set; }
        public string Password { get; set; }
    }
}
